export const
  ADD_POST       = "ADD_POST",
  EDIT_POST      = "EDIT_POST",
  DELETE_POST    = "DELETE_POST",

  ADD_COMMENT    = "ADD_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  GET_POSTS = "GET_POSTS",
  GET_POST_DETAILS = "GET_POST_DETAILS";
